apiVersion: platform.example.com/v1alpha1
kind: S3Bucket
metadata:
  name: twyetgf-pe-test
  namespace: default
spec:
  parameters:
    bucketName: twyetgf-pe-test
    region: us-east-1
  compositeDeletePolicy: Delete
  writeConnectionSecretToRef:
    name: twyetgf-pe-test-conn
